name: plexmediaserver
version: 1.7.2.3878-8088811b8
summary: Unofficial snap for the Plex media server
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/
confinement: strict
grade: stable

apps:
  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  common:
    plugin: dump
    source: bin
    organize:
      server.sh: bin/server.sh
  plexmediaserver:
    plugin: nil
    build-packages:
      - wget
      - dpkg
    prepare: |
      wget https://downloads.plex.tv/plex-media-server/$SNAPCRAFT_PROJECT_VERSION/plexmediaserver_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    install: |
      dpkg-deb -x plexmediaserver_$SNAPCRAFT_PROJECT_VERSION_amd64.deb $SNAPCRAFT_PART_INSTALL
