name: plexmediaserver
version: 1.2.7.2987-1bef33a-1
summary: Unofficial snap for the Plex media server
architectures: [amd64]
description: |
  Plex organizes all of your personal media so you can easily
  access and enjoy it. See https://www.plex.tv/
confinement: devmode
grade: devel

apps:
  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - home
      - network-bind
      - removable-media

parts:
  common:
    plugin: dump
    source: bin
    organize:
      server.sh: bin/server.sh
  plexmediaserver:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/1.2.7.2987-1bef33a/plexmediaserver_1.2.7.2987-1bef33a_amd64.deb
